name: Build and deploy to GCP

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_URL: europe-north1-docker.pkg.dev/pgp-sandbox/cloud-run-source-deploy/gh-actions-frontend-test/gh-actions-frontend-test:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: Authenticate GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure docker
        run: gcloud auth configure-docker europe-north1-docker.pkg.dev # value should be sth like europe-north1-docker.pkg.dev

      - name: Docker Build
        run: docker build --build-arg VITE_REACT_APP_TEST_1=hardcoded-in-workflow-yml --no-cache -t $IMAGE_URL . -f Dockerfile

      - name: Docker Push
        run: docker push $IMAGE_URL

      - name: Update Cloud Run service
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: jokes
          image: europe-north1-docker.pkg.dev/pgp-sandbox/cloud-run-source-deploy/gh-actions-frontend-test/gh-actions-frontend-test
